language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN="
install:
  - "npm install grunt-cli codeclimate-test-reporter -g"
  - "npm install"
script:
  - "<%= buildTool %> ci"
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "iojs-v1"
  - "iojs-v2"
cache:
  directories:
    - 'node_modules'
